services:
  # Frontend service
  frontend:
    container_name: "frontend-container"
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      NEXT_PUBLIC_LIFF_ID: ${NEXT_PUBLIC_LIFF_ID}
    networks:
      - app-network

  # ngrok service
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      [
        "http",
        "--domain=comic-greatly-flamingo.ngrok-free.app",
        "frontend-container:3000",
        "--log=stdout",
        "--log-level=debug",
      ]
    ports:
      - 4040:4040
    depends_on:
      - frontend
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    networks:
      - app-network

  # Backend service
  backend:
    container_name: "backend-container"
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      TZ: Asia/Tokyo
    networks:
      - app-network

  # Database service
  db:
    container_name: db-container
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "5433:5432"
    networks:
      - app-network

  # Database GUI service
  db-gui:
    container_name: db-gui-container
    image: dpage/pgadmin4:8.14
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    networks:
      - app-network

# Volumes
volumes:
  postgres_data:
  pgadmin-data:

# Networks
networks:
  app-network:
    driver: bridge
